create table public.final_prediction (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text not null,
  matchnumber smallint null,
  selectedvalue text null,
  bgroup text null,
  bid numeric null,
  name text null,
  constraint final_prediction_pkey primary key (id)
) TABLESPACE pg_default;

create table public.prediction (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text not null,
  matchnumber smallint null,
  selectedvalue text null,
  bgroup text null,
  bid numeric null,
  name text null,
  constraint prediction_pkey primary key (id)
) TABLESPACE pg_default;
create index IF not exists idx_prediction_match_email_group on public.prediction using btree (matchnumber, email, bgroup) TABLESPACE pg_default;

create table public.matchdata (
  id smallint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  selectedvalue text null,
  bgroup text null,
  winner text null,
  winamount double precision null,
  name text null,
  matchnumber smallint null,
  constraint matchdata_pkey primary key (id)
) TABLESPACE pg_default;

create table public.leaderboard (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  matchnumber smallint null,
  winamount double precision null,
  name text null,
  bgroup text null,
  matchwinamount double precision null,
  constraint leaderboard_pkey primary key (id)
) TABLESPACE pg_default;

create table public.fixtures (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  matchnumber smallint null,
  dateutc timestamp with time zone null,
  home text null,
  away text null,
  location text null,
  matchdate date null,
  constraint fixtures_pkey primary key (id)
) TABLESPACE pg_default;

create table public.members (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text not null,
  name text null,
  bgroup text null,
  amount numeric null,
  constraint members_pkey primary key (id)
) TABLESPACE pg_default;

create table public.teams (
  id bigint generated by default as identity not null,
  shortname text null,
  fullname text null,
  constraint teams_pkey primary key (id)
) TABLESPACE pg_default;

create table public.otp (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text not null,
  otp numeric null,
  constraint otp_pkey primary key (id)
) TABLESPACE pg_default;

create table public.admins (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  email text null,
  constraint admins_pkey primary key (id)
) TABLESPACE pg_default;